### ISSUE TITLE
synchronize or update org.skrooge.yml with json build file

### ISSUE THREAD

**Issue by skierpage** [flathub/org.kde.skrooge#9]
Skrooge has its own [org.kde.skrooge.json](https://cgit.kde.org/skrooge.git/tree/org.kde.skrooge.json) file to build a flatpak, used by the kdeapps build.
I don't know if the separate org.kde.skrooge.yml here is still necessary.
If it is then two should be more in sync, e.g. the YML file could pick up the `config-opts "-DSKG_BUILD_TEST=OFF",` which avoids building the tests (unless the flathub flatpak build actually runs these tests!).
Also the specific qca version 2.1.3 with local patch for qca-openssl may no longer be needed; org.kde.skrooge.json just gets qca (now version 2.2.1) from git with no patches.

FYI I used http://convertjson.com/yaml-to-json.htm to make it easier to diff the two build config files, but it's still tricky because the modules are in different order, the yml has opensp and gengetopt as submodules of libofx, etc.

Thanks for providing this flatpak.

**Comment by nedrichards** [comment]
It's often expected that there's a slight difference between a project hosted flathub manifest for testing - which will usually be using the latest git master and dependencies and a flathub version which should be using release builds and the tested set of dependencies that the upstream developers want. However in both of those cases it seems like those would be valid improvements.

I've just checked and unlike a lot of the other KDE apps this one isn't actually updated and maintained by the KDE community yet - we'd certainly prefer that! As ever, just let the flathub team know the appropriate github usernames and they'll be added. Otherwise, for stuff like this - PRs welcome.
